# Generated by Django 3.0.5 on 2020-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201005_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
