# Generated by Django 3.0.5 on 2020-10-05 10:09
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_user_invitation'),
    ]

    operations = [
    ]
