# Generated by Django 3.0.5 on 2021-11-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211030_2107'),
        ('users', '0010_auto_20211101_1410'),
    ]

    operations = [
    ]
