# Generated by Django 3.1.1 on 2021-11-01 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211101_1410'),
        ('users', '0011_auto_20211030_2107'),
    ]

    operations = [
    ]
