# Generated by Django 3.0.5 on 2021-11-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20211101_1815'),
        ('users', '0012_merge_20211102_1151'),
    ]

    operations = [
    ]
