# Generated by Django 3.0.5 on 2021-11-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211101_1410'),
        ('users', '0012_auto_20211101_1512'),
    ]

    operations = [
    ]
