# Generated by Django 3.0.5 on 2021-11-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20211101_1728'),
        ('users', '0013_merge_20211102_1507'),
    ]

    operations = [
    ]
