# Generated by Django 3.0.5 on 2021-11-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20211102_1507'),
        ('users', '0014_merge_20211102_1403'),
    ]

    operations = [
    ]
