# Generated by Django 3.0.5 on 2021-11-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20211103_1341'),
        ('users', '0014_merge_20211104_1153'),
    ]

    operations = [
    ]
