# Generated by Django 3.0.5 on 2021-11-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211108_1215'),
        ('users', '0016_merge_20211105_1632'),
    ]

    operations = [
    ]
