# Generated by Django 3.0.5 on 2021-11-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211109_1458'),
        ('users', '0019_auto_20211109_1444'),
    ]

    operations = [
    ]
