# Generated by Django 3.0.5 on 2024-12-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20211113_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
