# Generated by Django 3.0.5 on 2025-01-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20241210_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
