# Generated by Django 3.0.5 on 2025-02-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
