# Generated by Django 3.0.5 on 2025-02-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expense_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
